const data = [
  {
    id: 1,
    title: "Portfolio",
    gitTitle: "portfolio",
    article: "This site",
    technology: "HTML, SCSS, React.js, TypeScript, Firebase",
    app: "https://portfolio-2bb32.web.app/",
    appName: "App",
    imgPath: "portfolio-top.png",
    imgDetailPathA: "portfolio-top-detail.png",
    imgDetailPathB: "portfolio-projects-detail.png",
    imgDetailPathC: "portfolio-resume-detail.png",
  },
  {
    id: 2,
    title: "Cats' Community",
    gitTitle: "cats-community",
    article: "This app is for people loving cats",
    technology: "HTML, SCSS, React.js, TypeScript, Firebase, Material UI",
    app: "https://cats-community.web.app/",
    appName: "App",
    imgPath: "cats' community-top.png",
    imgDetailPathA: "cats' community-top-detail.png",
    imgDetailPathB: "cats' community-login-detail.png",
    imgDetailPathC: "cats' community-chat-detail.png",
  },
  {
    id: 3,
    title: "WeatherAPI App",
    gitTitle: "weatherAPI-app",
    article: "This app is for searching the weather by city name",
    technology: "HTML, CSS, Node.js, Express, Bootstrap, Heroku",
    app: "https://weather-api-app908130.herokuapp.com/",
    appName: "App",
    imgPath: "weather app-top.png",
    imgDetailPathA: "weather app-top-detail.png",
    imgDetailPathB: "weather app-search-detail.png",
    imgDetailPathC: "weather app-daily-detail.png",
  },
  {
    id: 4,
    title: "Burger Heaven",
    gitTitle: "burger-delivery",
    article: "E-commerce MERN stack app to order burgers",
    technology:
      "HTML, TailwindCSS, React.js, Redux, TypeScript, Node.js, Express, MongoDB, Material UI, Netlify",
    app: "https://burger-heaven-5b683.netlify.app/",
    appName: "App",
    imgPath: "burger heaven-top.png",
    imgDetailPathA: "burger heaven-detail.png",
    imgDetailPathB: "burger heaven-detail2.png",
    imgDetailPathC: "burger heaven-sm.png",
  },
  {
    id: 5,
    title: "Game of Life",
    gitTitle: "game-of-life",
    article: "This app is conway's game app algorithm",
    technology: "JavaScript",
    imgPath: "game of life-world.png",
    imgDetailPathA: "game of life-world-detail.png",
    imgDetailPathB: "game of life-random.png",
    imgDetailPathC: "game of life-world-detail.png",
  },
  {
    id: 6,
    title: "MovieAPI App",
    gitTitle: "movieAPI-app",
    article: "This app is for searching movies info",
    technology: "HTML, CSS, TypeScript, Bootstrap, Heroku",
    app: "https://movie-api-app930812.herokuapp.com/",
    appName: "App",
    imgPath: "movie app-top.png",
    imgDetailPathA: "movie app-top-detail.png",
    imgDetailPathB: "movie app-hover-detail.png",
    imgDetailPathC: "movie app-detailpage-detail.png",
  },
  {
    id: 7,
    title: "Country Explorer(group project)",
    gitTitle: "country-explorer",
    article: "This app is for searching any country info",
    addInfo: "my role: darkmode, detail info as modal",
    technology: "HTML, CSS, JavaScript, Vercel",
    app: "https://country-explorer-mauve.vercel.app/",
    appName: "App",
    imgPath: "country explorer-top.png",
    imgDetailPathA: "country explorer-top-detail.png",
    imgDetailPathB: "country explorer-dark-detail.png",
    imgDetailPathC: "country explorer-detailpage-detail.png",
  },
  {
    id: 8,
    title: "Juno(group project)",
    gitTitle: "juno",
    article: "This app is Online Wedding Invitations App",
    addInfo: "my role: Front-end guest part",
    technology:
      "React, TailwindCSS, Redux-toolkit, Typescript, Lambda, Dynamodb, Swagger, Aws-apigateway, Serverless-framework, Figma",
    app: "https://juno-wedding.vercel.app/admin",
    appName: "App",
    imgPath: "juno top.png",
    imgDetailPathA: "juno detail1.png",
    imgDetailPathB: "juno detail2.png",
    imgDetailPathC: "juno detail3.png",
  },
];

export const resumeDataList = [
  {
    name: "Kyosuke Ito",
    intro: "I'm a Front-end developer in Vancouver",
    background:
      "I have a strong communication skills because I had been a sales person for 6years.\nMoreover, I have a great passion and skills to make web applications and sites to help people more convenient and enrich their lives.",
    workExperience: [
      "Front-end Developer - Nareban Co. Ltd - (Apr 2022 - present )",
      "Front-end Developer - Desafios Co. Ltd - (Jan 2022 - Apr 2022 )",
      "Sales representative - Santen Inc - (2014-2020)",
    ],
    education: [
      "Web development, CICCC - Cornerstone International Community College of Canada - (Sep 2021 - present)",
      "Bachelor of Liberal Arts, YOKOHAMA NATIONAL UNIVERSITY JAPAN (Apr 2009 - Mar 2014)",
    ],
  },
  {
    softSkillList: [
      "Leadership",
      "Collaboration",
      "Communication",
      "Critical Thinking",
      "Creativity",
      "Organization Skills",
      "Enthusiasm",
      "Work Ethic",
      "Problem Solving",
    ],
    technicalSkillList: [
      "React",
      "Node.js",
      "Next.js",
      "Redux",
      "Javascript",
      "TypeScript",
      "Python",
      "Django",
      "HTML",
      "CSS",
      "SCSS",
      "TailwindCSS",
      "Github",
      "Firebase",
      "MongoDB",
      "MySQL",
      "Webpack",
      "Jest",
      "Ensyme",
      "Vagrant",
      "Heroku",
      "Vercel",
      "Netlify",
    ],
  },
];

export const contactDataList = [
  {
    phone: "(236)833-8229",
    email: "kyosuke0215@gmail.com",
    github: "https://github.com/aujourdui",
    linkedIn: "https://www.linkedin.com/in/kyosuke-ito-506090a8/",
    medium: "https://medium.com/@kyosuke0215",
  },
];

export default data;
