const data = [
  {
    id: 1,
    title: "Portfolio",
    gitTitle: "portfolio",
    article: "This site",
    technology: "HTML, scss, React.js, firebase",
    appName: "App",
    imgPath: "portfolio-top.png",
    imgDetailPathA: "portfolio-top-detail.png",
    imgDetailPathB: "portfolio-projects-detail.png",
    imgDetailPathC: "portfolio-resume-detail.png",
  },
  {
    id: 2,
    title: "Cats' Community",
    gitTitle: "cats-community",
    article: "This app is for people loving cats",
    technology: "HTML, scss, React.js, firebase, Material UI",
    app: "https://cats-community.firebaseapp.com/",
    appName: "App",
    imgPath: "cats' community-top.png",
    imgDetailPathA: "cats' community-top-detail.png",
    imgDetailPathB: "cats' community-login-detail.png",
    imgDetailPathC: "cats' community-chat-detail.png",
  },
  {
    id: 3,
    title: "WeatherAPI App",
    gitTitle: "weatherAPI-app",
    article: "This app is for searching the weather by city name",
    technology: "HTML, CSS, Node.js, Express, bootstrap, heroku",
    app: "https://weather-api-app908130.herokuapp.com/",
    appName: "App",
    imgPath: "weather app-top.png",
    imgDetailPathA: "weather app-top-detail.png",
    imgDetailPathB: "weather app-search-detail.png",
    imgDetailPathC: "weather app-daily-detail.png",
  },
  {
    id: 4,
    title: "MovieAPI App",
    gitTitle: "movieAPI-app",
    article: "This app is for searching movies info",
    technology: "HTML, CSS, Javascript, bootstrap, heroku",
    app: "https://movie-api-app930812.herokuapp.com/",
    appName: "App",
    imgPath: "movie app-top.png",
    imgDetailPathA: "movie app-top-detail.png",
    imgDetailPathB: "movie app-hover-detail.png",
    imgDetailPathC: "movie app-detailpage-detail.png",
  },
  {
    id: 5,
    title: "Game of Life",
    gitTitle: "game-of-life",
    article: "This app is conway's game app algorithm",
    technology: "JavaScript",
    imgPath: "game of life-world.png",
    imgDetailPathA: "game of life-world-detail.png",
    imgDetailPathB: "game of life-random.png",
    imgDetailPathC: "game of life-world-detail.png",
  },
  {
    id: 6,
    title: "Country Explorer(group project)",
    gitTitle: "country-explorer",
    article: "This app is for searching any country info",
    addInfo: "my role: darkmode, detail info as modal",
    technology: "HTML, CSS, Javascript, Vercel",
    app: "https://country-explorer-mauve.vercel.app/",
    appName: "App",
    imgPath: "country explorer-top.png",
    imgDetailPathA: "country explorer-top-detail.png",
    imgDetailPathB: "country explorer-dark-detail.png",
    imgDetailPathC: "country explorer-detailpage-detail.png",
  },
];

export const skillList = [
  {
    softSkillList: [
      "Leadership",
      "Collaboration",
      "Communication",
      "Critical Thinking",
      "Creativity",
      "Organization Skills",
      "Enthusiasm",
      "Work Ehic",
      "Problem Solving",
    ],
    technicalSkillList: [
      "React",
      "Node.js",
      "Next.js",
      "Redux",
      "Javascript",
      "TypeScript",
      "HTML",
      "CSS",
      "scss",
      "Github",
      "firebase",
      "MongoDB",
      "MySQL",
      "Webpack",
      "Jest",
      "Ensyme",
      "Vagrant",
      "Heroku",
      "Vercel",
    ],
  },
];

export default data;
