const data = [
  {
    id: 1,
    title: "Portfolio",
    gitTitle: "portfolio",
    article: "This site",
    technology: "HTML, scss, React.js, TypeScript, firebase",
    app: "https://portfolio-2bb32.web.app/",
    appName: "App",
    imgPath: "portfolio-top.png",
    imgDetailPathA: "portfolio-top-detail.png",
    imgDetailPathB: "portfolio-projects-detail.png",
    imgDetailPathC: "portfolio-resume-detail.png",
  },
  {
    id: 2,
    title: "Cats' Community",
    gitTitle: "cats-community",
    article: "This app is for people loving cats",
    technology: "HTML, scss, React.js, TypeScript, firebase, Material UI",
    app: "https://cats-community.web.app/",
    appName: "App",
    imgPath: "cats' community-top.png",
    imgDetailPathA: "cats' community-top-detail.png",
    imgDetailPathB: "cats' community-login-detail.png",
    imgDetailPathC: "cats' community-chat-detail.png",
  },
  {
    id: 3,
    title: "WeatherAPI App",
    gitTitle: "weatherAPI-app",
    article: "This app is for searching the weather by city name",
    technology: "HTML, CSS, Node.js, Express, bootstrap, heroku",
    app: "https://weather-api-app908130.herokuapp.com/",
    appName: "App",
    imgPath: "weather app-top.png",
    imgDetailPathA: "weather app-top-detail.png",
    imgDetailPathB: "weather app-search-detail.png",
    imgDetailPathC: "weather app-daily-detail.png",
  },
  {
    id: 4,
    title: "MovieAPI App",
    gitTitle: "movieAPI-app",
    article: "This app is for searching movies info",
    technology: "HTML, CSS, JavaScript, bootstrap, heroku",
    app: "https://movie-api-app930812.herokuapp.com/",
    appName: "App",
    imgPath: "movie app-top.png",
    imgDetailPathA: "movie app-top-detail.png",
    imgDetailPathB: "movie app-hover-detail.png",
    imgDetailPathC: "movie app-detailpage-detail.png",
  },
  {
    id: 5,
    title: "Game of Life",
    gitTitle: "game-of-life",
    article: "This app is conway's game app algorithm",
    technology: "JavaScript",
    imgPath: "game of life-world.png",
    imgDetailPathA: "game of life-world-detail.png",
    imgDetailPathB: "game of life-random.png",
    imgDetailPathC: "game of life-world-detail.png",
  },
  {
    id: 6,
    title: "Country Explorer(group project)",
    gitTitle: "country-explorer",
    article: "This app is for searching any country info",
    addInfo: "my role: darkmode, detail info as modal",
    technology: "HTML, CSS, JavaScript, Vercel",
    app: "https://country-explorer-mauve.vercel.app/",
    appName: "App",
    imgPath: "country explorer-top.png",
    imgDetailPathA: "country explorer-top-detail.png",
    imgDetailPathB: "country explorer-dark-detail.png",
    imgDetailPathC: "country explorer-detailpage-detail.png",
  },
];

export const resumeDataList = [
  {
    name: "Kyosuke Ito",
    intro: "I'm a Front-end developer in Vancouver",
    background:
      "I have a strong communication skills because I had been a sales person for 6years.\nMoreover, I have a great passion and skills to make web applications and sites to help people more convenient and enrich their lives.",
    workExperience: [
      "Front-end Developer - Desafios Co. Ltd - (Jan 2022 - present)",
    ],
    education: [
      "Web development, CICCC - Cornerstone International Community College of Canada - (Sep 2021 - present)",
      "Bachelor of Liberal Arts, YOKOHAMA NATIONAL UNIVERSITY JAPAN (Apr 2009 - Mar 2014)",
    ],
    qualifications: [
      "The Complete 2021 Web Development Bootcamp(Certificate on Udemy, Sep 2021)",
      "The Complete React Developer Course (W/ Hooks and Redux) (Certificate on Udemy, Oct 2021)",
      "Next.js & React - The Complete Guide (incl. Two Paths1) (Certificate on Udemy, Nov 2021)",
      "Understanding TypeScript 2021 Edition (Certificate on Udemy, Nov 2021)",
    ],
  },
  {
    softSkillList: [
      "Leadership",
      "Collaboration",
      "Communication",
      "Critical Thinking",
      "Creativity",
      "Organization Skills",
      "Enthusiasm",
      "Work Ethic",
      "Problem Solving",
    ],
    technicalSkillList: [
      "React",
      "Node.js",
      "Next.js",
      "Redux",
      "Javascript",
      "TypeScript",
      "HTML",
      "CSS",
      "scss",
      "Github",
      "firebase",
      "MongoDB",
      "MySQL",
      "Webpack",
      "Jest",
      "Ensyme",
      "Vagrant",
      "Heroku",
      "Vercel",
    ],
  },
];

export const contactDataList = [
  {
    phone: "(236)833-8229",
    email: "kyosuke0215@gmail.com",
    github: "https://github.com/aujourdui?tab=repositories",
    linkedIn: "https://www.linkedin.com/in/kyosuke-ito-506090a8/",
    medium: "https://medium.com/@kyosuke0215",
  },
];

export default data;
