const data = [
  {
    id: 1,
    title: "Portfolio",
    gitTitle: "portfolio",
    article: "This site",
    technology: "HTML, scss, React.js, firebase",
    appName: "App",
    imgPath: "portfolio-top.png",
    imgDetailPath: "portfolio-top-detail.png",
  },
  {
    id: 2,
    title: "Cats' Community",
    gitTitle: "cats-community",
    article: "This app is for people loving cats",
    technology: "HTML, scss, React.js, firebase, Material UI",
    app: "https://cats-community.firebaseapp.com/",
    appName: "App",
    imgPath: "cats' community-top.png",
    imgDetailPath: "cats' community-top-detail.png",
  },
  {
    id: 3,
    title: "WeatherAPI App",
    gitTitle: "weatherAPI-app",
    article: "This app is for searching the weather by city name",
    technology: "HTML, CSS, Node.js, Express, bootstrap, heroku",
    app: "https://weather-api-app908130.herokuapp.com/",
    appName: "App",
    imgPath: "weather app-top.png",
    imgDetailPath: "weather app-top-detail.png",
  },
  {
    id: 4,
    title: "MovieAPI App",
    gitTitle: "movieAPI-app",
    article: "This app is for searching movies info",
    technology: "HTML, CSS, Javascript, bootstrap, heroku",
    app: "https://movie-api-app930812.herokuapp.com/",
    appName: "App",
    imgPath: "movie app-top.png",
    imgDetailPath: "movie app-top-detail.png",
  },
  {
    id: 5,
    title: "Game of Life",
    gitTitle: "game-of-life",
    article: "This app is conway's game app algorithm",
    technology: "JavaScript",
    imgPath: "game of life-world.png",
    imgDetailPath: "game of life-world-detail.png",
  },
  {
    id: 6,
    title: "Country Explorer(group project)",
    gitTitle: "country-explorer",
    article: "This app is for searching any country info",
    addInfo: "my role: darkmode, detail info as modal",
    technology: "HTML, CSS, Javascript, Vercel",
    app: "https://country-explorer-mauve.vercel.app/",
    appName: "App",
    imgPath: "country explorer-top.png",
    imgDetailPath: "country explorer-top-detail.png",
  },
];

export default data;
